# Generated by Django 4.2.5 on 2024-10-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_movies_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('imdb_id', models.CharField(max_length=255, unique=True)),
                ('tmdb_id', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('tv_show_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media.tvshows')),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('season_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media.seasons')),
            ],
        ),
    ]
