# Generated by Django 4.2.5 on 2024-10-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_tvshows_seasons_episodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodes',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='seasons',
            old_name='tv_show_id',
            new_name='tv_show',
        ),
    ]
