# Generated by Django 4.2.5 on 2024-10-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_alter_episodes_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_link', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
