# Generated by Django 4.2.5 on 2024-10-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_servers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servers',
            old_name='server_link',
            new_name='link',
        ),
    ]
